baseURL = "https://mikanbearer.github.io/"
languageCode = "en-us"



DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "腦袋空空日記"
theme = "hugovuetifymix"
metaDataFormat = "yaml"

#disqusShortname = "XXX"
#googleAnalytics = "XXX"

disablePathToLower = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[Params]
  #homeTitle = "BLOG" # Set a different text for the header on the home page
  subtitle = "要是能寫得下去就好了"
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  preserveTaxonomyNames = true

