baseURL = "https://mikanbearer.github.io/"
languageCode = "en-us"



DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Unnamed Diary"
#theme = "test"
theme = "test"
metaDataFormat = "yaml"

disqusShortname = "mikanmimi"
#googleAnalytics = "XXX"

disablePathToLower = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[Params]
  keywords = "tech-note"
  description = "只是筆記"
  #homeTitle = "BLOG" # Set a different text for the header on the home page
  subtitle = "要是能寫得下去就好了"
  mainSections = ["post","posts"]
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  preserveTaxonomyNames = true


[outputs]
  home = ["HTML"]
  page = ["JSON"]
  section = ["JSON", "HTML"]



[Author]
  name = "Zhang San"
  imageURL = ""
  email = ""
  facebook = ""
  github = "mikanbearer"
  gitlab = ""
  
  twitter = ""
  linkedin = ""
  xing = "username"
  snapchat = ""
  instagram = ""
  youtube = ""

  codepen = ""
