baseURL = "https://mikanbearer.github.io/"
languageCode = "en-us"



DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "活到老學到死"
theme = "hugo-vue-mix"
metaDataFormat = "yaml"

disqusShortname = "mikanmimi"
#googleAnalytics = "XXX"

disablePathToLower = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[Params]
  #homeTitle = "BLOG" # Set a different text for the header on the home page
  subtitle = "要是能寫得下去就好了"
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  preserveTaxonomyNames = true






[Author]
  name = "Zhang San"
  website = "yourwebsite.com"
  email = "youremail@domain.com"
  facebook = "username"
  github = "username"
  gitlab = "username"
  bitbucket = "username"
  twitter = "username"
  reddit = "username"
  linkedin = "username"
  xing = "username"
  stackoverflow = "users/XXXXXXX/username"
  snapchat = "username"
  instagram = "username"
  youtube = "user/username" # or channel/channelname
  soundcloud = "username"
  spotify = "username"
  bandcamp = "username"
  itchio = "username"
  vk = "username"
  paypal = "username"
  telegram = "username"
  500px = "username"
  codepen = "username"
  mastodon = "url"
  kaggle = "username"
  weibo = "username"
  slack = "username"